In [55]:
import pandas as pd
import random
import string

In [34]:
no_podcasts = 200
genres = ['Comedy', 'Fitness & Nutrition', 'Society & Culture', 'News & Politics', 'Management & Marketing', 'TV & Film', 'Kinds & Family', 'Music', 'Video Games', 'Self-Help']

In [15]:
df_raw = pd.read_csv('./databases/poddf.csv')
df_raw.head()

,index,Name,Rating_Volume,Rating,Genre,Description
0,0,Fresh Air,10188,4.46133,Arts,"Fresh Air from WHYY, the Peabody Award-winning..."
1,0,The Moth,10154,4.69982,Performing,"Since its launch in 1997, The Moth has present..."
2,0,99% Invisible,12303,4.8693,Design,"Design is everywhere in our lives, perhaps mos..."
3,0,iFanboy.com Comic Book Podcast,1335,4.79551,Visual,The iFanboy.com Comic Book Podcast is a weekly...
4,0,Myths and Legends,11128,4.88282,Literature,"Jason Weiser tells stories from myths, legends..."

In [41]:
df_raw.drop(df_raw[df_raw['Rating_Volume']=='Not Found'].index, inplace=True)
df_raw.sort_values(by=['Rating_Volume'],inplace=True,ascending=False)
df_raw = df_raw[['Name', 'Genre','Description']]
df_raw.head()

,Name,Genre,Description
7591,The Jasta Show,Music,"Musician, former television host, and podcaste..."
10430,"Sincerely, X",Society & Culture,"Some stories are too sensitive, painful or pot..."
7849,Whistlestop: Presidential History and Trivia,History,John Dickerson of Slate’s Political Gabfest re...
9622,Twenty Thousand Hertz,Music,The stories behind the world's most recognizab...
7225,God Centered Mom Podcast | Don't Mom Alone,Kinds & Family,LIfe is messy. Some days (some hours) are hard...

In [43]:
df_genres = df_raw.groupby(['Genre']).size()
df_genres.sort_values(ascending=False)

Genre
Comedy                        244
Investing                     242
Performing                    240
Christianity                  240
Video Games                   240
History                       240
News & Politics               239
Tech News                     239
Alternative Health            238
Management & Marketing        238
Places & Travel               238
Fitness & Nutrition           237
TV & Film                     237
Kinds & Family                237
Language Courses              237
Careers                       234
Food                          234
Self-Help                     234
Outdoor                       234
Literature                    234
Other Games                   233
Professional                  233
Music                         233
Medicine                      232
Spirituality                  232
Personal Journals             231
College & High School         228
Hobbies                       228
Visual                        227
Sexuality                     227
                             ...
Design                        209
Social Sciences               202
Islam                         200
Podcasting                    190
Amateur                       186
Automotive                    182
Other                         176
Gadgets                       174
Judaism                       164
Fashion & Beauty              159
Non-Profit                    140
Buddhism                      138
Society & Culture             118
Educational Technology        116
National                      115
Aviation                      105
Local                          84
Sports & Recreation            77
Science & Medicine             56
Government & Organizations     51
Technology                     44
Shopping                       44
Education                      42
Business                       42
Arts                           35
Hinduism                       32
Games & Hobbies                23
Regional                       17
Health                         15
Religion & Spirituality        11
Length: 67, dtype: int64

In [47]:
df_select = df_raw[df_raw['Genre'].isin(genres)]
df_select = df_select.rename(columns={'Name':'pod_name', 'Genre': 'category', 'Description':'description'})
df_select.head()

,pod_name,category,description
7591,The Jasta Show,Music,"Musician, former television host, and podcaste..."
10430,"Sincerely, X",Society & Culture,"Some stories are too sensitive, painful or pot..."
9622,Twenty Thousand Hertz,Music,The stories behind the world's most recognizab...
7225,God Centered Mom Podcast | Don't Mom Alone,Kinds & Family,LIfe is messy. Some days (some hours) are hard...
4255,Fly By Nite: A Fortnite Podcast,Video Games,HandsomePhantom.com is bringing you all the la...

In [52]:
df_sample = df_select.sample(n=no_podcasts)
print(len(df_sample.index))

200

In [64]:
coverart_links = []
letters = string.ascii_letters + string.digits
for p in range(len(df_sample.index)):
    link = "http://imgur.com/"
    for i in range (0,20):
        link += random.choice(letters)
    coverart_links.append(link)

In [66]:
df_sample['cover_image'] = coverart_links
df_sample.head()

,pod_name,category,description,cover_image
7734,1A,News & Politics,1A is home to the national conversation. Joshu...,http://imgur.com/wMID0Oi6KQAXRhrNsNIS
6296,The Keto Diet Podcast,Fitness & Nutrition,"Support your low-carb, high-fat life with The ...",http://imgur.com/Hh9UdCPEsO90nOxocpoM
2775,Laser Time,Comedy,Laser Time is a show featuring folks in the vi...,http://imgur.com/SoAbG3pXiHfK9REyQipv
2461,Simple Pin Podcast: Simple ways to boost your ...,Management & Marketing,Kate Ahl is the owner and founder of Simple Pi...,http://imgur.com/qlOp8DVJqcSHw6bOii2g
10527,TD Jakes Podcast,Society & Culture,"Insightful, relevant conversations between T. ...",http://imgur.com/Uo1p1bV5T7w30r7OhLo3

In [67]:
df_sample.to_csv('./generated/podcasts.csv')